server:
    port: 8763
spring:
    application:
        name: remoteConfigServer
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/007-is-life/mySpringCloud.git
                    searchPaths: remoteConfigServer/src/main/resources/remoteConfig
                    username: 007-is-life
                    password: 5190689Yjf.
            label: master
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/